### ISSUE TITLE
Link "Connected Assets functionality" leads back to same page

### ISSUE THREAD

**Issue by ackoch** [AdobeDocs/experience-manager-65.en#166]
Issue in help/assets/use-assets-across-connected-assets-instances.md

The link "see Connected Assets functionality in Experience Manager as a Cloud Service" is leading to the very same document (under a different URL)

**Comment by ashishguptaiitb** [comment]
Hi @ackoch , we have separate articles for AEM 6.5 and AEM as a Cloud Service. The 6.5 article links to CS article.

> Experience Manager 6.5 Assets works with Experience Manager as a Cloud Service. For more information, [see Connected Assets functionality in Experience Manager as a Cloud Service](https://docs.adobe.com/content/help/en/experience-manager-cloud-service/assets/admin/use-assets-across-connected-assets-instances.html)

**Comment by ackoch** [comment]
I just realized that ... only the contents look the same. This is confusing.. This can be maybe improved when the cross-links between each other are bit more explicit... Like "a _similar_ article on 6.5" something like that

**Comment by aheim0** [comment]
Tracked with CQDOC-16999.

**Comment by ashishguptaiitb** [comment]
@ackoch , we discussed this internally and I've made these updates. 
* The version applicability of articles is highlighted in the breadcrumbs at the top. 
* Editorially, I've mentioned the AEM versions twice -- in the sentence and in the link text.

I'm closing this issue hoping that it helps. If we hear similar feedback about version applicability confusion, we shall revisit at a template level rather than editorial fixes.
