### ISSUE TITLE
Referenced document/workaround do not load

### ISSUE THREAD

**Issue by riosmart** [AdobeDocs/experience-manager-65.en#173]
The Widgets API documentation appears to be broken. There are many links to it from AEM 6.5 documentation. 

There is a referenced link for "CQ.form.SmartImage component" in the following documentation that does not load:
https://docs.adobe.com/content/help/en/experience-manager-65/developing/components/classic-ui-components/xtypes.html

**A ticket was opened earlier this year but the workaround doesn't work anymore either.** 
**https://github.com/AdobeDocs/experience-manager-65.en/issues/68**

**Comment by anujkapo** [comment]
Thanks, @riosmart. We have recently moved our documentation from docs.adobe.com platform to the Experience League. The documentation mentioned by you now redirects to:
https://experienceleague.adobe.com/docs/experience-manager-65/developing/components/classic-ui-components/xtypes.html?lang=en#using-xtypes-classic-ui
Let me know if that's not the behavior you are experiencing.

**Comment by riosmart** [comment]
Thanks for the quick reply @anujkapo, I meant to reference the CQ.form.RichText[1] page within the document you provided.

1.) https://helpx.adobe.com/experience-manager/6-5/sites/developing/using/reference-materials/widgets-api/index.html?class=CQ.form.RichText

**Comment by anujkapo** [comment]
Thanks, @riosmart for the clarification. We will take a look.

**Comment by anujkapo** [comment]
Tracked using CQDOC-17106.

**Comment by bohnertchris** [comment]
As reported in #68, this comes down to an engineering and documentation platform issue, and unfortunately we still do not have any more information regarding an expected fix.

Though the suggested workaround does not work due to the retirement of docs.adobe.com, the 6.1 documentation can still be access as a package.

https://experienceleague.adobe.com/docs/experience-manager-release-information/aem-release-updates/previous-updates/aem-previous-versions.html
