### ISSUE TITLE
MS Dynamics OData ADFS config Prerequisites

### ISSUE THREAD

**Issue by f1205** [AdobeDocs/experience-manager-65.en#188]
Issue in ./help/forms/using/ms-dynamics-odata-configuration.md

I ran into a problem when running the command (_Add-AdfsClient -ClientId "\<Client-ID\>" -Name "\<name\>" -RedirectUri "\<redirect-uri\>" -GenerateClientSecret_) in step 1 on our ADFS Server running Windows Server 2012 R2. Found out that the GenerateClientSecret switch is not available on 2012 R2 but is on Windows Server 2016.

2016: https://docs.microsoft.com/en-us/powershell/module/adfs/add-adfsclient?view=win10-ps
2012R2: https://docs.microsoft.com/en-us/powershell/module/adfs/add-adfsclient?view=winserver2012r2-ps

**Comment by TylerRush** [comment]
CQDOC-17246

**Comment by anujkapo** [comment]
@f1205, Can you try executing the command without -GenerateClientSecret? In addition, leave the Client Secret field empty while configuring the data source.
Can you test if it works and let us know. We will update the documentation so that other customers using the Windows Server 2012 R2 operating system can benefit from this information as well. I will keep the issue open for a week and wait for your confirmation. Thanks!

**Comment by anujkapo** [comment]
@f1205, please let us know if you tried executing the recommended solution. We will update the documentation based on your confirmation. Closing this one as there has been no response for two weeks. Please feel free to reopen or create a new one.
