### ISSUE TITLE
Wrong diagram pictures

### ISSUE THREAD

**Issue by yyamada-adobe** [AdobeDocs/experience-manager-65.en#19]
Issue in help/sites-developing/the-basics.md

Diagram pictures in "Introduction to Sling" section seems to be wrong, showing Coral UI rather than sling processing.

**Comment by aheim0** [comment]
Thank you for raising this issue. However, I have just checked and it looks as if this issue has been fixed.

There was an issue with with images when we migrated content to this platform, this was recently addressed (i.e. since you registered this issue) and the images updated - the image you mentioned was one of them. 

Please let us know if you are still seeing any issues with this, or any other image.
