### ISSUE TITLE
The Single Responsibility Principle is not about doing just one thing

### ISSUE THREAD

**Issue by puradawid** [AdobeDocs/experience-manager-65.en#236]
Issue in ./help/sites-developing/software-architecture.md

[This](https://blog.cleancoder.com/uncle-bob/2014/05/08/SingleReponsibilityPrinciple.html) is the official definition of SRP, as it originates from Robert C. Martin, and it doesn't say:

> each module, class, method, etc, should do only one thing.

but actually means: 

> Gather together the things that change for the same reasons. Separate those things that change for different reasons.

which, rephrasing the context of this quotation, could be something like:

> each module, class, method, etc. should represent the interests of one and the only one unit within an organization

The proposed rephrasing may be changed (given I am not a native speaker), although "doing one thing" is an exaggeration of the referenced principle.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
Thank you for taking time to report this, @puradawid. As you know, volumes have been written on each part of the SOLID acronym and the article is intended for awareness rather than exhaustive explantation. Therefore I have tweaked the S to emphasize responsibility and added a note for further reading.

Resolved in commit a8dd817 in 6.4 and 58b60ad in 6.5.
