### ISSUE TITLE
Configuring replication with data store

### ISSUE THREAD

**Issue by bartoszWesolowski** [AdobeDocs/experience-manager-65.en#376]
Issue in ./help/sites-deploying/data-store-config.md

I am trying to set up set up AEM with File Data Store and documentation seems unclear. It seems that when setting this up replication agent should be also configured properly with Binary less Serialization type but this is not stated clearly in the documentation.

In the documentation I can only see `Configuring binaryless replication with Amazon S3` under `DataStore Caching` section which suggest that replication agent has to be changed only for S3. Is that correct or is it documentation issue?

**Comment by anujkapo** [comment]
Thanks, @bartoszWesolowski. We will take a look.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by thedoc31** [comment]
@bartoszWesolowski Binaryless replication is only useful when a shared datastore is set up for Author and Publishers. If you aren't sharing a datastore, the full binary blob needs to be replicated and stored on each Publisher in your farm.

Binaryless means the Author assigns the blob a hash and writes the full blob data into the shared datastore. When an object is replicated, Author will send only the hash rather than the full blob of data. When a Publisher needs to retrieve that blob, they will consult their local cache first to see if the blob is already there. If it isn't, they will check for that blob on the shared datastore and cache it locally.

**Comment by raimanS** [comment]
@bartoszWesolowski The explanation seemed sufficient so I marked the issue as completed. We will evaluate updating the documentation and I will post here if/when the update goes live. Thanks for bringing this to our attention.

**Comment by bartoszWesolowski** [comment]
@raimanS 

Explanation is great but it does not resolved the original issue with the documentation. I think it should contain explanation where, why and how binary less replication agent should be configured as it is still unclear. @thedoc31 comment will definitely help with that.
