### ISSUE TITLE
Update documentation for Language Copy (rename, move of pages) and how the process works 

### ISSUE THREAD

**Issue by cbCode123** [AdobeDocs/experience-manager-65.en#383]
Issue in ./help/sites-administering/msm-best-practices.md

The page move operation is documented for live copy but not also for language copy.
Customer requires the documentation to be updated with best practice regarding how an editor handles move pages (when different new page name is provided) in the structure for language copy and how do you get this change into other languages of the multiple language copies.

Documentation is required for below action/scenario:
Customer content is created in language-master/English and there are 25 other language copies. 
Now, the user moves the page in English and new page name is provided.
The documentation should specify how to handle this move operation and how to get the same change into the 25 other language copies.

[Logged by Support]

**Comment by cbCode123** [comment]
Customer requires detailed documentation what AEM capabilities are in regards to maintaining language copies (rename, move of pages) and how the process works - this is currently not available at all in the documentation

**Comment by bohnertchris** [comment]
Thank you for the issue, @cbCode123. We will review.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
I added a section describing the behavior: https://experienceleague.adobe.com/docs/experience-manager-65/administering/introduction/tc-manage.html#move-source

**Comment by Mahesh-Pati** [comment]
There is no option to create a language copy of a page , to one of the existing project language code. Currently this is possible only via siteadmin.
Via sites language copy option, the language code for existing project is not availaible under target language code. That is why , siteadmin (classic UI) is used to achieve this which works fine.
 
This is expected behavior in AEM or There should be an option to create language copy via references, like update option is given for existing project.
