### ISSUE TITLE
Tag title cannot contain a slash /

### ISSUE THREAD

**Issue by suchawla1989** [AdobeDocs/experience-manager-65.en#429]
Issue in ./help/sites-developing/framework.md

https://experienceleague.adobe.com/docs/experience-manager-65/developing/platform/tagging/framework.html?lang=en

Tag title cannot contain a slash could be added with in the documentation.

Label: DocBugBlitz2023

**Comment by bohnertchris** [comment]
Thanks for the suggestion, but tag title can contain a slash. The name of the tag is generated automatically by AEM based on the title and any slash will be replaced by AEM with a dash in order to be JCR-compliant. If a user tries to enter slash in the name field by hand, validation is performed and AEM will not allow it to be saved.

I think a link to the JCR naming conventions might be more appropriate here as well as from the create/managing tags page.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
A link to JCR naming conventions was added as part of commit d056d61.
