### ISSUE TITLE
Update OSGi Tools link reference

### ISSUE THREAD

**Issue by lha-adobe** [AdobeDocs/experience-manager-65.en#44]
Issue in help/sites-deploying/osgi-configuration-settings.md

In the Note stating "The AEM OSGi Config Details tool can be used to list the default OSGi configurations." -- please update the link to point to [1].  The current link is no longer maintained and we have ingested the items to our helpx documents.

[1] https://helpx.adobe.com/experience-manager/kb/tools/aem-tools.html

Please change all related versions of the document to use this helpx doc [1] also

{{Logged by Support}}

**Comment by bohnertchris** [comment]
@lha-adobe we appreciate the feedback. Which tool on the new page actually replaces the "The AEM OSGi Config Details tool"? Or do they all do part of what it used to do? Thanks for the clarification.

**Comment by lha-adobe** [comment]
Working: https://helpx.adobe.com/experience-manager/kb/tools/aem-tools.html 

Non-working: https://www.aemstuff.com/osgi.html

We are currently linking to the non-working.  Fix is to link the working on our documents.

**Comment by bohnertchris** [comment]
Thank you for responding so promptly, @lha-adobe . It is clear that we need to point to https://helpx.adobe.com/experience-manager/kb/tools/aem-tools.html instead of https://www.aemstuff.com/osgi.html. However https://helpx.adobe.com/experience-manager/kb/tools/aem-tools.html lists a number of tools. The linked text in question that needs to be updated states "The AEM OSGi Config Details tool can be used to list the default OSGi configurations." However the page to which we now need to link contains multiple tools. The question I have is which one of those tools is the "AEM OSGi Config Details tool"?

**Comment by lha-adobe** [comment]
The specific link [1] to use to replace broken link -- this is our helpx OSGi configuration comparing tool

[1] https://helpx.adobe.com/experience-manager/kb/tools/osgi-configuration-diff.html

**Comment by bohnertchris** [comment]
Great. Thank you.

**Comment by bohnertchris** [comment]
This has been fixed via commit e513fe0 in this repo as well as via commit 6758a93 in the experience-manager-64.en repo.
