### ISSUE TITLE
Permissions of  package-builders group

### ISSUE THREAD

**Issue by vdhaliwa** [AdobeDocs/experience-manager-65.en#67]
Issue in help/assets/use-assets-across-connected-assets-instances.md

In the "Users and groups involved" table, it is mentioned that DAM distributor users should be part of package-builders group. This group does not exist OOTB.

Provide the details of ACL's/permissions this user should have on remote Asset instance.

**Comment by ashishguptaiitb** [comment]
Thanks Vishu for sharing this. I shall look into it soon.

**Comment by ashishguptaiitb** [comment]
The article for AEM 6.5 is updated at https://docs.adobe.com/content/help/en/experience-manager-65/assets/using/use-assets-across-connected-assets-instances.html.

The same issue existed in and is fixed in [Cloud Service article](https://docs.adobe.com/content/help/en/experience-manager-cloud-service/assets/admin/use-assets-across-connected-assets-instances.html) too.
Thanks for sharing.
