### ISSUE TITLE
referenced document does not load

### ISSUE THREAD

**Issue by hamid-k50** [AdobeDocs/experience-manager-65.en#68]
Issue in help/sites-developing/xtypes.md

There is a referenced link for "CQ.form.SmartImage component" in the following documentation that does not load:

https://docs.adobe.com/content/help/en/experience-manager-65/developing/components/classic-ui-components/xtypes.html

<support reported>

**Comment by vdhaliwa** [comment]
Hello Doc team,

We have received another case for the same issue.
 CQ > Ext > form or CQ > form classes does not load.

Please help fix it asap.

**Comment by aheim0** [comment]
Thank you for highlighting this.
As this content is generated by Engineering we have contacted them. However, as this relates to the classic UI we cannot guarantee a response time. Thank you for your understanding.

**Comment by aheim0** [comment]
We have heard back that unfortunately this is a known issue, due to the documentation platform (an old one) still being used for that content. For that reason we cannot expect a fix, but as we're due to migrate that content we will ensure that it is fully operational on the replacement platform (when that happens). We have this on the list of requirements and will test once we gain access.
 
In the meantime we can offer the workaround of accessing the 6.1 version, as the Widgets-API has not changed since then. The link is:
- https://docs.adobe.com/content/docs/en/aem/6-1/ref/widgets-api/index.html?class=CQ.form.SmartImage
 
Apologies for the inconvenience and hope this will help.

**Comment by aheim0** [comment]
As the situation is outside our control at the moment, and a workaround has been provided, we are closing this issue.
